services:
  nestjs-crud-app-server:
    container_name: nestjs-crud-app-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - dev_net
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - devdb

networks:
  dev_net: